### ISSUE TITLE
How to prevent email spoofing and phishing attacks?

### ISSUE THREAD

**Issue by inetbiz** [StrikeHawk-ecommerce/whmcs-responsive-email-templates#3]
It came up in a recent discussion that criminals could spoof these email templates to get your customers to click in their system. Rework all templates and require response online. No hyperlinks in the content.

**Comment by THEMVFFINMAN** [comment]
I was actually guided here while searching for email phishing templates. Thanks!

**Comment by inetbiz** [comment]
@THEMVFFINMAN not good that results show up for that! =)
