### ISSUE TITLE
Clarification RE html headers etc

### ISSUE THREAD

**Issue by solaceten** [StrikeHawk-ecommerce/whmcs-responsive-email-templates#7]
So, I notice that with WHMCS there does not appear to be anyway to add the usual stuff like;

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>something</title>
</head>
<body>`

I tried adding these, but to no avail. I think messages often go to spam because of this.

Opinions?

**Comment by inetbiz** [comment]
You don't add headers. You can set the CSS, the top of the template and the footer of the templates from Settings = General => Mail. I have included my head template and foot template that you can modify. The others are the body that you edit in WHMCS => Email templates.

**Comment by solaceten** [comment]
Thanks for the fast reply.  Yes, I know how to modify all of those.  Your examples are also very nice, thank you.

It's more a comment about the fact that WHMCS doesn't use any of the standard header stuff...  If you examine the source in any email client, you can see whmcs doesn't send them - most other html emails do have them.  That's why e.g. Outlook often send whmcs mails to spam/junk!

I don't think there is any way to include them, even if you wanted to.

Have you tested your template with Hotmail / Outlook ? You should....

**Comment by inetbiz** [comment]
Yes I have. inline CSS3 plus embedded stylesheet in this template ensures the template renders as intended. You should take up your issue with whmcs.com directly.
