### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by chessmango** [StrikeHawk-ecommerce/whmcs-responsive-email-templates#9]
The LICENSE file states cc0 for this code, but README.md states otherwise. I'm happy to assume that README.md takes precedence, but I note that it's CC-BY-NC. How... would these templates be used for non-commercial purposes when dealing with WHMCS, an inherently commercial platform? Free webhosting only?
Just wanting to clarify here. :D I'd imagine for the most part people will ignore the licensing, but I'd like to do right. :P

**Comment by inetbiz** [comment]
The stylesheet is a creative work. It is copyright. Just don't want someone taking everything from here and try to sell it.

**Comment by chessmango** [comment]
Great, thanks! And good work! :)
